### ISSUE TITLE
User signup schema validation fails to catch duplicate email address

### ISSUE THREAD

**Issue by hmstepanek** [hypothesis/product-backlog#964]
https://sentry.io/organizations/hypothesis/issues/873372193/events/46465463202/

For some reason, user's are signing up again even though they have already signed up and are hitting an integrity error for duplicate email address in the user table. We have a schema check in place for this that searches the user table and validates that that email is not present before continuing the signup process (aka actually submitting the db query to add the new user). So in theory, this integrity error should never happen because we have a schema validation in place that should catch this before it makes the db call. 

Interestingly, the last login in metabase shows the same timestamp as these integrity errors. Meaning the user was logged in at or around the time of the signup integrity error. If the user was somehow logged in while still issuing a signup request this would explain how the validation passed but the actual act of adding it to the db failed since the logic is as follows for the schema validation:
```
    user = models.User.get_by_email(request.db, value, request.default_authority)
    if user and user.userid != request.authenticated_userid:
        msg = _("Sorry, an account with this email address already exists.")
        raise colander.Invalid(node, msg)
```
So note if somehow the user was logged into their account while also trying to re-signup, the schema validation that checks for a duplicate email would pass (since the userid of the logged in user would match the userid found in the db for that email address).

**Comment by seanh** [comment]
The linked Sentry issue seems to have been resolved. Should we close this?

**Comment by hmstepanek** [comment]
No, I think I accidentally clicked resolve and couldn’t figure out how to undo it. It’s still a problem.

**Comment by hmstepanek** [comment]
I recreated the scenario with two workers where the user issues a signup request and then while that's being handled (after the redirect occurs but before the schema email check), the user logs in. However, since the request.authenticated_userid at the time of the signup is None, it stays None for the duration of that request thus, despite the user logging in this will not register until after that request is finished so it throws the expected duplicated email address error message. 

Looking at the Sentry issues, it appears the signup datetime is the same as the datetime of the incidents thus this leads me to believe this issue may be related to a duplicated signup happening at or almost the same time in two different requests (a race condition between two near simultaneous signup requests). Really the only way to catch this sort of thing is at the db layer like we are already doing so I'm not sure there is anything to do here other than track down why we've been seeing so many of these duplicated requests. (We already have several other issues filed on this problem so I'm thinking perhaps we should just close this one.)

**Comment by seanh** [comment]
I think catching it at DB level is fine, but rather than 500ing the code should catch the IntegrityError from the DB and turn it into a nice "An account with the email address already exists" error page. If conflicting requests come in at the same time in a race condition then both requests can't succeed, one of them is going to have to fail, but it should fail without crashing h.

**Comment by lyzadanger** [comment]
If we want to be really fancy/correct about this, we'd raise an HTTP 409 (Conflict) and make sure that there is an exception view that will match for that context and display a nicely-formatted error (presumably similarly to the way we handle more common HTTP 4xx errors).

**Comment by hmstepanek** [comment]
I looked into disabling the submit signup button after it's clicked but it appears it's already getting disabled so I don't think there's much left to do here. I'm gonna go ahead and close this.
